# Generated by Django 3.1.2 on 2020-10-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('lecturer', models.CharField(max_length=150, null=True)),
                ('credits', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('term', models.CharField(choices=[('odd', 'odd'), ('even', 'even')], default='odd', max_length=5, null=True)),
                ('room', models.CharField(choices=[('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='2020/2021', max_length=10, null=True)),
            ],
        ),
    ]
