# Generated by Django 3.1.2 on 2020-10-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
