# Generated by Django 3.1.2 on 2020-10-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story1', '0006_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='identitiy_number',
            new_name='identity_number',
        ),
    ]
