# Generated by Django 3.1.2 on 2020-10-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story1', '0007_auto_20201017_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
