dist: xenial
language: python
python:
- 3.8
before_install:
- python --version
- pip install -U pip
- pip install codecov
env:
- DJANGO_VERSION=3.1.1
install:
- pip install -r requirements.txt
- pip install -q Django==3.1.1
- python setup.py -q install
before_script:
- python manage.py collectstatic --noinput
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test story6.tests
- coverage run --source='story6' manage.py test story6
- coverage report -m
after_success:
- codecov
before_deploy: echo 'ready?'
deploy:
  provider: heroku
  api_key:
    secure: CsXDz5RWplU+jFwk4kjhBDV1NPoqJxsghdz0UpUYMen8Eb3foitllh5jdO07Y1zsd2vPCuoMSZ4UbQlpCVhQslj5wgJsXC0xemCLCEWYee7YFP4V6jYGHcb+FkKM7qdX2QJ1IPKVsRDpxRRpVGITHs4kVZy+lCehqjzLKqWw3nBvDmA1PqEpUMpDpbhbZj066NtoEP1H6OYJ0e92WkYlPaf5ik/uOlkfcHM8u1dXUddSlNgTKAwxny+TPTNUcBOKS3UkIO9Cpe53PI3Rktc936uJaQML5j/GqOlFdCIUbhmPsFxi88JSVRlaFeDMKdY2oMBiFP1cf6NAOtYGd87J+qA/TETozGmmrwR1EL8VGqXxOG/8cORLIGAdWjPSspI7Xvx2tYZeuQBABWx3Bo4i3bzKF5ZNQ4le8HFqxvkUsCO9FhQ7sxL5fIBoJR+rfixGyAVHbrFsOsT2FhjXv6pdYQW8oSXWBdGZPMW6bWqqxhsxNCn5BkdbqoUnWe05uEfpMwrl0ePfoTEaWBq0DwlYeq+t6RqjQkMhzaMNLGkPVrn0GveXToPKvdDQNggJhrUHYe/aSp9CsrkYAcQqwJOU6Fx32K4mdugA91aLlEdpXAQ/Q/ppEUte7vyIf2VqVhf6x6XjKRhR+itunoLlhesqJac3AZCHkUhU9goRsMYzUTc=
  app: faisal-ppw
  on:
    repo: faisaladisoe/story-ppw
after_deploy: "./deployment.sh"
