dist: xenial
language: python
python:
- 3.8
before_install:
- python --version
- pip install -U pip
- pip install codecov
env:
- DJANGO_VERSION=3.1.1
install:
- pip install -r requirements.txt
- pip install -q Django==3.1.1
- python setup.py -q install
before_script:
- python manage.py collectstatic --noinput
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test story8.tests
- coverage run --source='story8' manage.py test story8
- coverage report -m
after_success:
- codecov
before_deploy: echo 'ready?'
deploy:
  provider: heroku
  api_key:
    secure: qLgc7c9iQXpWumlYtAfzbcbVODiqh8jXJF3ru4iJI1/NOcx+zTJj9EtRoabPF40Rcv4qTdVRj/PNYltJOxGJRdyLrfWK9bJsuckk79j66sHbTbuUyVJzewlhVF1rnlOsaWd4OvO4z6M01Zh3x9ttDdncL8bSNw54P9/4mDbGn70WeolvghFWgFwRUh7h1gS+caon0p49gUnSpZpWV3chU1926zyEYDabEv/f5tajuvtZNL2WKcdqkR3nvyHh9o3PB5s4ai2qZn/s9L44cLM7BsplPPtbcHvgPNN5fMb4OTDqUWuRWSlyACAOaW8hMRnrJLxaowwGRDGXkCdh26KnUSeJVf6TIV2JjW8xCuX/hL88l6EW20awPgMBJttYGL9x7KLJj+V32c8iwf4Lpk6fDwZTvljgw/QG9rftUEIysVZnGKmaGtyzapN9ODUCHIcUmc16Ka1WTLNz5CBxqQ/vAqlBmUrtbZ4HxMtEWsepjUuxJy0nZlyZdG+ihVicZ+TBCTFYkJXrDItxXrpjE/lJNbtDVOdTqVmLFyny7TMe0ujJGVe9v1MjHNi23kDi/d1PfMHXPI4+YMUvFwxFYtbB9MZqqzLnlNcUeNTYyPPFnm7FehfZmpMkYpxvvOUcsjvDbg5ORF3Xs6Ul7XDDQr+6dpUvO4P5dV6DZ040/8ZTLxc=
  app: faisal-ppw
  on:
    repo: faisaladisoe/story-ppw
after_deploy: "./deployment.sh"
