language: python
python:
  - "3.8"
env:
  - DJANGO_VERSION=3.1.1
install:
  - pip install -r requirements.txt
  - pip install -q Django==3.1.1
  - python setup.py -q install
script:
  - pytest